version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: car_rent
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "7890:5432"
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

volumes:
  postgres_data:
